# Change these first
owner: yukbid # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Home
    url: https://yukbid.com
  - name: API Server
    url: https://api.yukbid.com/version.txt
  - name: Yukbid URL Shortener
    url: https://url.yukb.id/version
#  - name: Yukbid Staging
#    url: https://yukbid.lyr.id/homepage

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.yukb.id
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /statuspage
  logoUrl: https://yukbid.com/assets/img/brand_primary.svg
  favicon: https://yukbid.com/assets/favicon.ico
  name: "Yukbid's Status Page"
  themeUrl: https://appify.org/lyrid.css
  introTitle: "Yukbid's Status Page"
  navbar:
    - title: Status Page
      href: /
    - title: Yukbid
      href: https://www.yukbid.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
